# Generated by Django 4.1.3 on 2022-11-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='氏名')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('postal_code', models.CharField(max_length=8, verbose_name='郵便番号')),
                ('address', models.CharField(max_length=128, verbose_name='住所')),
            ],
            options={
                'verbose_name': '顧客',
                'verbose_name_plural': '顧客',
            },
        ),
    ]
